apiVersion: v1
kind: Service
metadata:
  name: health-check-svc
  labels:
    app: health-check
spec:
  selector:
    app: health-check
  type: NodePort
  ports:
    - name: http          
      port: 5000
      targetPort: 5000
      nodePort: 30080
