apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-check-servicemonitor
  namespace: monitoring         
  labels:
    release: monitoring        
spec:
  selector:
    matchLabels:
      app: health-check         
  namespaceSelector:
    matchNames:
      - default                 
  endpoints:
    - port: http               
      path: /metrics
      interval: 15s
      scheme: http
